# fly.toml app configuration file generated for aoc-2023 on 2023-12-01T19:34:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aoc-2023"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
